old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        balance:
            class: App\Producer\BalanceOperationProducer
            connection:       default
            exchange_options: { name: 'task', type: direct }

    consumers:
        balance:
            connection:       default
            exchange_options: { name: 'task', type: direct }
            queue_options:    { name: 'balance' }
            callback:         App\Consumer\BalanceOperationConsumer
